version: 2.1
jobs:
    Gwb:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu

workflows:
    version: 2.1
    build:
        jobs:
            - Gwb